coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true
  
  # 指定覆盖率文件的格式
  parsers:
    coveralls:
      target_files:
        - coverage.json

comment:
  layout: "header,diff,flags,files,footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "node_modules"
  - "target"
  - "_coverage"