coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

comment:
  layout: "header,diff,flags,files,footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

parsers:
  lcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - "node_modules"
  - "target"
  - "_coverage"
  - "**/*.json"