name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MoonBit
      uses: moonbitlang/setup-moonbit@v1
      with:
        version: latest
    
    - name: Build and Test
      run: |
        moon check
        moon test
    
    - name: Generate Coverage Data
      run: |
        moon coverage clean
        moon coverage analyze
    
    - name: Generate Coverage Report
      run: |
        moon coverage report -f coveralls -o coverage.json
        ls -la coverage.json
    
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.json
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        verbose: true