name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MoonBit
      uses: moonbitlang/setup-moonbit@v1
      with:
        version: latest
    
    - name: Build and Test
      run: |
        moon check
        moon test
        moon run src/test.mbt
    
    - name: Generate Coverage Report
      run: |
        # 运行MoonBit测试并生成覆盖率
        moon test --coverage
        moon coverage bisect.coverage --format=lcov > coverage.lcov
    
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.lcov
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false