name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MoonBit
      uses: hustcer/setup-moonbit@v1
      with:
        version: "latest"
    
    - name: Check MoonBit installation
      run: |
        moon version --all
        which moon
    
    - name: Install dependencies
      run: |
        moon install
    
    - name: Check project
      run: |
        moon check
    
    - name: Run tests with coverage
      run: |
        moon test --enable-coverage
    
    - name: Generate coverage reports
      run: |
        moon coverage report -f cobertura -o coverage.xml
        moon coverage report -f html
    
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: |
          coverage.xml
          _coverage/
    
    - name: Build project
      run: |
        moon build